# Generated by Django 4.2.16 on 2024-11-24 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_fabrica_id_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
