# Generated by Django 4.2.16 on 2024-11-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_f_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fabrica',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
