# Generated by Django 4.2.16 on 2024-11-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_fabrica_pais_alter_fabrica_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='imagen',
            field=models.URLField(null=True),
        ),
    ]
