# Generated by Django 4.2.16 on 2024-12-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_fabrica_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabrica',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(default='https://st3.depositphotos.com/16203680/19307/v/950/depositphotos_193076602-stock-illustration-question-mark-hand-drawn-symbol.jpg'),
        ),
    ]
